# Generated by Django 6.0.5 on 2026-05-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('monthly_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_scale', models.CharField(choices=[('RES', 'Residential Rooftop (<10 kW)'), ('COM', 'Commercial Roof (10 kW - 100 kW)'), ('MW', 'Megawatt / Industrial Utility Scale (>100 kW)')], max_length=3)),
                ('financial_assistance', models.CharField(choices=[('LOAN', 'Loans Only'), ('SUBSIDY', 'Subsidy Assistance Only'), ('BOTH', 'Both Loans & Subsidies'), ('NONE', 'Self-Funded')], max_length=8)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(help_text='e.g., Coimbatore, Tamil Nadu', max_length=100)),
                ('category', models.CharField(choices=[('RES', 'Residential Rooftop'), ('COM', 'Commercial Setup'), ('MW', 'Megawatt Scale / Industrial')], default='RES', max_length=3)),
                ('capacity_kw', models.DecimalField(decimal_places=2, help_text='Capacity in kW or MW', max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/images/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo embed link for drone footage', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
